
/**:
  ros__parameters:
      # Context / inference parameters
    context:
      n_ctx: 8192
      n_batch: 512
      n_predict: 256

    # GPU / backend parameters
    gpu:
      n_gpu_layers: 20

    # CPU parameters
    cpu:
      n_threads: -1

    # Prompt & chat parameters
    prompt:
      system_prompt_type: ChatML

    model: 
      repo: "mradermacher/SpatialThinker-7B-i1-GGUF"
      filename: "SpatialThinker-7B.i1-Q4_K_M.gguf"
      
    mmproj:
      repo: "mradermacher/SpatialThinker-7B-GGUF"
      filename: "SpatialThinker-7B.mmproj-f16.gguf"

